apiVersion: v1
kind: Service
metadata:
  name: devops-secret
  namespace: development
spec:
  type: NodePort
  selector:
    app: ziyotekapp
  ports:
    - port: 8090
      targetPort: 80
      nodePort: 31777
